volumes:
  rotation-data:
    external: true
  pgadmin:
    external: true
services:
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - rotation-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=rotationHop
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  rotation-app:
    build:
      context: ./ffxiv_django
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./rotation_hop:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://products:password@postgres:5432/rotationHop
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 240
  ffxiv_react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ffxiv_react:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_ROTATION_HOP: http://localhost:8080
      REACT_APP: http://localhost:3000
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - /pgadmin/var/lib/pgadmin4
    ports:
      - "8060:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rbbitphoto@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
